series: Basic OpenGL with GLFW
title: Compute Shaders
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use Compute shaders to operate on data within a buffer.
language: C++
tags:
  - Graphics
extra_resources:
  - link: https://www.opengl.org/wiki/Compute_Shader
    title: General Information on compute shaders.
  - link: https://www.opengl.org/wiki/Shader_Storage_Buffer_Object
    title: Information on Shader Storage Buffer Objects (buffers used in compute shaders)
connections:
  - series: Basic OpenGL with GLFW
    title: Fragment Shaders